### ISSUE TITLE
Mantener seguimiento del tipo y las dimensiones de los tipos de literales de vector

### ISSUE THREAD

**Issue by BraulioVM** [BraulioVM/pl#14]
En la regla `VECTOR` de `gramatica.y` no se tiene implementado nada para detectar
el tipo y las dimensiones del vector.

**Comment by BraulioVM** [comment]
Arreglado en https://github.com/BraulioVM/pl/commit/51d32f6a308b648f8b540d5ad34f0a9fb2a9bbb0. No se soportan literales de matrices porque el guión de la práctica solo habla de literales de vectores.

**Comment by namasme** [comment]
Pero entonces nunca se va a poder trabajar con matrices, ¿no?
