### ISSUE TITLE
Implementar comprobación semántica de dimensiones en la multiplicación

### ISSUE THREAD

**Issue by BraulioVM** [BraulioVM/pl#15]
Actualmente en la multiplicación de escalares solo se comprueba que los tipos de los factores son numéricos iguales. En el apéndice A del guión de prácticas viene qué tipo de multiplicaciones se deben permitir. También hay que implementar la comprobación semántica para la multiplicación matricial

**Comment by namasme** [comment]
En realidad es más que el producto porque también se permite la suma, diferencia y división.
A todo esto, ¿tiene sentido que sólo permitamos operar con escalares del mismo tipo? Parece que añade complejidad teniendo que comprobar las constraints.

**Comment by BraulioVM** [comment]
Bueno recuerdo que en algún lado venía algo así como que los tipos iban a ser estrictos y que no se iba a permitir ningún tipo de casteo. Yo esto lo he interpretado como que tampoco se harían casteos en la suma. Preguntaremos al profesor en la siguiente clase

**Comment by BraulioVM** [comment]
Queda implementar la multiplicación y división elemento a elemento
