### ISSUE TITLE
Refactorizar el makefile

### ISSUE THREAD

**Issue by BraulioVM** [BraulioVM/pl#2]
Hay mucha redundancia en el makefile que podría ser muy peñazo de mantener en el futuro. 

Para resolver esta issue:
1. Investigar qué podemos hacer para reducir la redundancia en el `makefile`. Esto podría involucrar reestructurar el repositorio si hiciera falta.
2. Tomar tales medidas

**Comment by namasme** [comment]
@BraulioVM échale un oculus
