### ISSUE TITLE
Tener cuidado con la asociatividad de operadores y sus precedencias

### ISSUE THREAD

**Issue by BraulioVM** [BraulioVM/pl#4]
En 74f54bb se ha definido la asociatividad de algunos operadores y sus precedencias. Cuando empecemos a parsear los ejemplos que hemos escrito tendremos que tener especial cuidado con:

1. La precedencia de la multiplicación y la división respecto a la suma. Creo que esto tal como está definido debería funcionar bien.
2. La precedencia de `+` y `-` como operadores unarios. Creo que ahora mismo estos operadores tienen menor precedencia que el resto. Esto funciona bien para `-a*b = -(a*b)` pero quizá hay casos en los que no tiene sentido (¿`-a||b = -(a||b)`?)
3. La asociatividad izquierda para todos los operadores binarios. Para los operadores que sean asociativos supongo que no hay ningún problema con elegir asociatividad por la izquierda ¿Tiene sentido la asociatividad por la izquierda para todos nuestros operadores binarios no asociativos? Lo tiene para la división por ejemplo ¿qué hay del resto?

**Comment by namasme** [comment]
Los dos commits que hablaban de #4 en realidad hablaban de #6 (my bad)

**Comment by BraulioVM** [comment]
Esto se arregló siguiendo el criterio del apéndice y el profesor nos lo corrigió al revisar la sintaxis
