### ISSUE TITLE
Mejores declaraciones "sean"

### ISSUE THREAD

**Issue by BraulioVM** [BraulioVM/pl#6]
Investigar la posibilidad de:

1. Eliminar del todo el bloque `sean` si no se desea declarar ninguna variable. Actualmente
    se puede hacer `sean.` pero no es tan satisfactorio.
2. No requerir un punto y coma después de la declaración de la última variable. Actualmente
    hay que hacer `sean entero x;.` pero estaría bien que bastara con `sean entero x.`
3. También es un poco raro poner `sean entero x.` en vez de `sea entero x` pero esto es un poco pijada. Quizá se pueda hacer fácilmente de todas formas

**Comment by namasme** [comment]
5cc39c90d6f2e7553fd33b8a8a7cc32ebcc95d0e resuelve la issue.
