### ISSUE TITLE
No se puede llamar a procedimientos con una cadena como argumento

### ISSUE THREAD

**Issue by namasme** [BraulioVM/pl#8]
`ARGUMENTOS_PROCEDIMIENTO -> LISTA_EXPR -> EXPR | EXPR COMA LISTA_EXPR`, pero `CADENA` no se acepta como `EXPR` https://github.com/BraulioVM/pl/blob/2693b7e2da7e20f1b1fdfb897ef1be7fc88e7a54/compilador/gramatica.y#L184-L189

**Comment by BraulioVM** [comment]
Cierro porque `cadena` no es un tipo de dato de nuestro lenguaje.
